### ISSUE TITLE
particles not correctly rendered in master / linux OF9.0

### ISSUE THREAD

**Issue by jamet** [moostrik/ofxFlowTools#10]
hi, 
it seems like a great addon, but unfortunatly i can't make it work correctly on my laptop.

With the current master, nothing happens or show on the screen except the cam, and some vector and force field when in 8 draw modewhen pressing mousse buttons.

i tried to look a bit at what could possibly go wrong, but i didn't find much.... 

i tried to tweek a bit ftShader.h, and changed 
     quad.setMode(OF_PRIMITIVE_TRIANGLE_FAN);

with 
     quad.setMode(OF_PRIMITIVE_TRIANGLES);

and at some moment, i can see some particles when pressing mousse buttons.

i don't understand much when it comes to shaders, but it could be possible that my render is set to bad rendering mode that doesn't show particle correctly?

i had a kind of like problem with some bezier curves, the curve wasn't properly textured, because of a glPolygonMode uncorrectly set to gl_point instead of gl_fill....

let me know if i can help debugging this, i really would like to see that addon working as it looks great.

forgot to mention, i'm running lubuntu 14.04 on a asus core i5 with geforce850m (support opengl 4.5)

**Comment by moostrik** [comment]
Unfortunately i cannot reproduce the error (on mac)
