### ISSUE TITLE
VS 2015 src file names dont match

### ISSUE THREAD

**Issue by elburz** [moostrik/ofxFlowTools#12]
It seems like in VS2015 on Windows 10, oF 0.9.2, if I open the project, under the src folder in the VS solution, there is main.cpp, flowTools.h, and flowTools.cpp, but in the actual src folder, and in main.cpp it actually references ofApp.h and ofApp.cpp. 

Not sure if it's related to the build errors I'm having but it's definitely strange.

**Comment by moostrik** [comment]
I'm not working on windows these days, but when i do I will look into this issue

**Comment by moostrik** [comment]
still no windows
