### ISSUE TITLE
void getMaxArrowLenth() unexpected return type

### ISSUE THREAD

**Issue by elburz** [moostrik/ofxFlowTools#14]
I was getting a return value error on line 72 of ftVelocityField.h because the .get() is apparently returning a value, not void:

`void 	getMaxArrowLenth()					{ return maxArrowLength.get(); }`

By changing that line to the below, it compiles successfully:

`float	getMaxArrowLenth()					{ return maxArrowLength.get(); }`

While we're here getMaxArrowLenth() has a misspelling in Length (missing a g).

System:
oF 0.9.2
VS2015 Community
Windows 10
nVidia 970M

**Comment by moostrik** [comment]
fixed, thanks!
