### ISSUE TITLE
Export/Import mouse drawn fields

### ISSUE THREAD

**Issue by elburz** [moostrik/ofxFlowTools#16]
Trying to add a system to export and import the mouse drawn fields so that you can not only save the parameters but the full state of the system once you get a look you like. Started by saving the fields as an image and loading them and adding the density and velocity back to the fluidSimulation, but looking through the source, seems like there's a lot more going on with the mouse and having to applyForce() at every mouse position. Any thoughts on how this could be spliced in easiest? 

Curious if I can just write the ftFbo from the image, but that seems like a preview more than anything?...or am I better off trying to just save and re-execute mouse movements?

I see a saveValue function, which seems to save every force vector in the field, maybe I can output those and then iterate through them again and apply them? 

Let me know your thoughts. Thanks!

**Comment by elburz** [comment]
Been trying to use ofxMouseTrap to record the mouse paths and replay them on load but no luck. I can redraw my path in the window, but it doesn't seem to apply any mouseForces. I'm wondering if this is because of the fact that ftDrawMouseForces has it's own mouseMoved and mouseDragged functions listening for physical mouse movements and not just whatever ofxMouseTrap is doing to simulate mouse movement and clicks inside the window?

**Comment by elburz** [comment]
Finally got something implemented. Saving the paths to XML via ofxMouseTrap, reloading them on launch, iterating through the path, then creating ofMouseEventArgs() for every element and feeding them into the mouseForces.setMouseDragEvent().

Might be a nice additional feature to add, I can push up some code next week once I clean it up a bit if you're interested

**Comment by moostrik** [comment]
The fluid velocity is calculated with float textures as it can be negative. As far as I know it is not possible to save negative colors in an image. But you could try to save the velocity image as an xml file.
You should use the velocity from the simulation and not  the one that is used for visualisation as the latter is sort of normalized. (0 - 0.5 is negative velocity, .5 is no velocity, and 0.5 - 1 is positive velocity)

Your current method is also interesting.
