### ISSUE TITLE
Simulation speed

### ISSUE THREAD

**Issue by elburz** [moostrik/ofxFlowTools#17]
Might be my lack of experience with fluid simulations, but curious if there's any easy way to take the simulation's current state and just make it slower...

I'm finding that if I get a nice look, then try to slow it down, it then changes the look as it's computing differently. Maybe not something that's possible with fluid simulations in general, but i'd be curious. I was running my app at 60fps going to try 30fps to see if that gives a similar effect then I can interpolate frames possibly.

**Comment by elburz** [comment]
Latest attempt was trying to control/lessen the time delta, which maybe works a bit, been looking at the screen too long to tell...

**Comment by elburz** [comment]
Seems like other apps render at the rate to get the look, then use a cache system and interpolate between all the cached states at the desired rate...doesn't sound like it would be an easy addon, heh.

**Comment by moostrik** [comment]
The speed parameters should enable you to do this as well
