### ISSUE TITLE
iPad or Inverted Version

### ISSUE THREAD

**Issue by Nemquae** [moostrik/ofxFlowTools#20]
Hi, thanks for this framework.  Been a great resource so far.

We've been using this for a while and having some success, but not we'd like to try to get it running on the iPad.  After setting up an xcode project with the proper settings, the biggest issues seem to lie with converting to OpenGLES (3 ideally, but 2 can work too).  Any insights on how to go about that?

GL_VERTEX_PROGRAM_POINT_SIZE and GL_GEOMETRY_SHADER_EXT are undefined, and I'm guessing we can't use geometry shaders at all.  I'm not an expert on shaders, but I know enough to follow your code so far - just not sure what would need to be changed exactly.  For example, I could just disable the debug views that use geometry shaders, since those aren't critical.  Or I see in some shader wrapper classes that you once used GL_POINT_SMOOTH instead of GL_VERTEX_PROGRAM_POINT_SIZE.  Is it possible to go back to that?

Also, previously I tried to invert the colors so that the fluid simulation would have a white background with a natural blend of colors.  It turns out that I would have to re-derive some of the fluid equations to do that correctly, as just inverting colors doesn't yield a natural blend.  Do you know of a good resource or a better hack for that?

**Comment by dokosoft** [comment]
any progress on this ?
