### ISSUE TITLE
error: unknown type name 'ftAreaFlow'

### ISSUE THREAD

**Issue by aprowe** [moostrik/ofxFlowTools#22]
Hello, 

I'm trying to build off of master, and building the extended example comes up with the error:
```
error: unknown type name 'ftAreaFlow'
```

I couldn't find any reference to that in the repository, is the example out-of-date?

Awesome tool, Thanks!

**Comment by aprowe** [comment]
BTW I see that you made some changes today, so no worries if master just isn't stable right now

**Comment by moostrik** [comment]
ftAreaFlow was just renamed to ftAverageFlow. If you rebuild the examples using the project generator they should work.
