### ISSUE TITLE
this error only in debug / Windows

### ISSUE THREAD

**Issue by carlesgutierrez** [moostrik/ofxFlowTools#23]
This error is in **debug mode** for Windows
That is happening in of V0.1 RC4 VS2017  or event in 0.98 VS2015

`->\addons\ofxflowtools\src\core\ftflow.h(33): error C4716: 'flowTools::ftFlow::setVisualizationToggleScalar': must return a value`

![errorindebug32bits](https://user-images.githubusercontent.com/203877/44456571-2b833f80-a601-11e8-809e-c317fdda5fbd.PNG)

**Comment by moostrik** [comment]
this was already fixed
