### ISSUE TITLE
Fluids or Particles not working for Windows

### ISSUE THREAD

**Issue by carlesgutierrez** [moostrik/ofxFlowTools#24]
Hello @moostrik , 
 As I commented in the OF [forum](https://forum.openframeworks.cc/t/ofxflowtools-optical-flow-fluid-dynamics-and-particles-in-glsl/15470/54?u=charli_e). at least in in this [commit  ](https://github.com/moostrik/ofxFlowTools/commit/c1df42a8899032d109c23aea4490674bcb073ef9)your addon is not drawing / calculating Fluids or Particles in Windows. Just Optical Flow mode draw is visible.

To debug this issue -> because all cacls are done in shaders, and I coudl draw all returned textures. If after opticalFlow ( that is working ok), I should go for velocityBridgeFlow, right? there is any kind of drawScalar mode for velocityBridgeFlow that I can check?

I'm compiling ok for both, core and extended, examples[ only in release mode.](https://github.com/moostrik/ofxFlowTools/issues/23)
For the extended example: When the App starts, a small particles is moving once from right to left inside of the ROI area defined. 🏄

I'm on windows10 64 bits / Nvidia 1060.

**Comment by moostrik** [comment]
> there is any kind of drawScalar mode for velocityBridgeFlow that I can check?

in both examples there are 14 visualisation modes, each supporting scalar draw

**Comment by carlesgutierrez** [comment]
Hello @moostrik !
I've started with ftAverageFlow functions, because opticalFlow works. 

And after some debugging, I've found that there are NaN values are received from inputPixels

> float* floatPixelData = inputPixels.getData();

That affects some calcs like:

> 	void ftAverageFlow::getMeanStDev(vector<float> &_v, float &_mean, float &_stDev) {

that is using accumulate function and nan values affect into that calculation. **std::accumulate** is always returning nan.  I've found a temporal solution by doing my own accumulation function, avoiding Nan numbers.  

```
       //--------------------------------------------------------------
	float ftAverageFlow::accumulateFloatNan(vector<float> _v) {
		float auxAccum = 0;
		for (int i = 0; i < _v.size(); i++) {
			if (!isnan(_v[i])) {
				auxAccum += _v[i];
			}
		}
		return auxAccum;
	}

	//--------------------------------------------------------------
	void ftAverageFlow::getMeanStDev(vector<float> &_v, float &_mean, float &_stDev) {
		//float mean = std::accumulate(_v.begin(), _v.end(), 0.0f) / (float)_v.size();
		float mean = accumulateFloatNan(_v) / (float)_v.size();
		cout << "mean = " << mean << endl;
		std::vector<float> diff(_v.size());
		std::transform(_v.begin(), _v.end(), diff.begin(), std::bind2nd(std::minus<float>(), mean));
		float sq_sum = std::inner_product(diff.begin(), diff.end(), diff.begin(), 0.0f);
		float stDev = std::sqrt(sq_sum / _v.size());
		
		_mean = mean;
		_stDev = stDev;
	}
```

![averageworking](https://user-images.githubusercontent.com/203877/44854729-a84d9380-ac69-11e8-955f-f4ef98aec2aa.PNG)

Now Flow Average is visible. But are those values ok? Or that should return also negative values.

Mac compiler might be accept NAN pixel values for accumulation. Or is not returning any NAN values from inputPixels.getData();

Any other way to solve it?

**Comment by moostrik** [comment]
The magnitude should always be in range 0...1
The x and y should be in range -1...1, but it seems x and y are not visible in your picture

On mac I don't get any Nan values.
This might actually be the problem why the fluid does not work!
So the solution for all of the windows problems could be in the opticalFlow shader.
Although at first glance i do not see how it could return Nan...

**Comment by carlesgutierrez** [comment]
ok, just filtering Nan values for vel results:

```
//--------------------------------------------------------------
	void ftAverageFlow::update() {
		ftUtil::toPixels(inputFbo, inputPixels);
		float* floatPixelData = inputPixels.getData();
		
		vector<float> totalVelocity;
		totalVelocity.resize(numChannels, 0);
		
		int numPixels = inputWidth * inputHeight;
		for (int i=0; i<numPixels; i++) {
			double mag = 0;
			for (int j=0; j<numChannels; j++) {
				float vel = floatPixelData[i * numChannels + j];
				if (!isnan(vel)) {
					totalVelocity[j] += vel;
					mag += vel * vel;
				}
			}
			magnitudes[i] = sqrt(mag);
		}
		getMeanStDev(magnitudes, meanMagnitude, stdevMagnitude);
...
```
 FT_VELOCITY 
![componentsvelworking](https://user-images.githubusercontent.com/203877/44861782-8d831b00-ac79-11e8-881b-1f4d5499aec0.PNG)

**Comment by carlesgutierrez** [comment]
> The magnitude should always be in range 0...1
> The x and y should be in range -1...1, but it seems x and y are not visible in your picture

Before I was setting Average as FT_VELOCITY_NORM, now I've see has no sense. Just FT_VELOCITY it's ok.
> On mac I don't get any Nan values.

Yeah, here it is.
> This might actually be the problem why the fluid does not work!

Sure. All is being processed at each shader, so Nan values might be giving errors ( 0's? ) over there, right?
> So the solution for all of the windows problems could be in the opticalFlow shader.

I will try to check this later. That Nan might not also be nice to handle over there. 
> Although at first glance i do not see how it could return Nan...

**Comment by moostrik** [comment]
I figured out one problem with flowtools on windows. 
Normalising a vector with a length of 0 in a shader results in unexpected behaviour.
On windows it returns nan on mac 0. A quick fix is to add a tiny value to the vector before normalising it.
This fix is implemented in the `Fluid-Rebuild `branch. Note: This branch is unstable and the fluid still does not work on windows

**Comment by carlesgutierrez** [comment]
Good catch! 👍
