### ISSUE TITLE
manage several opticalFlow regions dynamically

### ISSUE THREAD

**Issue by carlesgutierrez** [moostrik/ofxFlowTools#25]
Hello @moostrik , 
 I'm wondering If I can use your addon to read several areas at same time..
 I can handle serveral static ftAverageFlow areas in the way you setup the system.  

`flows.push_back(&temporalAverageFlowItem1);`
`flows.push_back(&temporalAverageFlowItem2);`
...

but if I want to have several dynamic areas : create and destroy them dynamically, I can not pass there just a pointer of something I'm not saving. Right? How I could do this? 

Another way I'm thinking about is just setup one ( full size ), and try to read pixel by pixel the OpticalFlow restults. Any tips how to do read several small regions or by pixel of a ftOpticalFlow?

**Comment by moostrik** [comment]
this is not an issue. 
You could play around with the region of interest (setRoi()) in the ftAverageFlow

**Comment by carlesgutierrez** [comment]
Sorry that I set this as an issue. I do not know where to ask you this. Where else I can write this feature?

Do you mean I can just set several ROI and read them as different results all in one frame? That would be so great! 

My best, would be to draw all the ROI's at same time so then drawVisualizer for all of them.  That, I got it only when adding static ftAverageFlow items into the system.

Ok, I've just tried what you suggested. But did not work for me. Only one is working at time.

I did this:

//Update
```
	opticalFlow.update();
	averageFlow.setInput(opticalFlow.getVelocity());
```

//Draw
```
	if (toggleAverageDraw) {
		ofEnableBlendMode(OF_BLENDMODE_ALPHA);
		for (int i = 0; i < myAvgFlowRois.size(); i++) {
			averageFlow.setRoi(myAvgFlowRois[i]);
			averageFlow.update();
			averageFlow.drawInput(myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight, myAvgFlowRois[i].width*densityWidth, myAvgFlowRois[i].height*densityHeight);
			averageFlow.drawVisualizer(myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight, myAvgFlowRois[i].width*densityWidth, myAvgFlowRois[i].height*densityHeight);
		}
	}
```

**Comment by carlesgutierrez** [comment]
I guess DrawVisualizer will not be possible, I will have to do my own I I want it. 

But, yes you were right. I can get different averageFlow results on the fly. I'm working on it.  I almost there: now I'm drawing the different results, but one item switched. If I have 3 ROIS -> 0 is 1. 1 is 2  and 2 is 0. 
 I you do not mind I will post it here: 
```

//Now all in Draw: 
	if (toggleAverageDraw) {
		ofEnableBlendMode(OF_BLENDMODE_ALPHA);
		for (int i = 0; i < myAvgFlowRois.size(); i++) {
			averageFlow.setInput(opticalFlow.getVelocity());
			averageFlow.update();
			
			averageFlow.setRoi(myAvgFlowRois[i]);
			averageFlow.drawInput(myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight, myAvgFlowRois[i].width*densityWidth, myAvgFlowRois[i].height*densityHeight);
			averageFlow.drawVisualizer(myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight, myAvgFlowRois[i].width*densityWidth, myAvgFlowRois[i].height*densityHeight);

			
			ofDrawBitmapStringHighlight("getStDevMagnitude -> " + ofToString(averageFlow.getStDevMagnitude(), 3), myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight-20);
			ofDrawBitmapStringHighlight("getComponent 0 -> " + ofToString(averageFlow.getComponent(0), 3), myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight - 60);
			ofDrawBitmapStringHighlight("getComponent 1 -> " + ofToString(averageFlow.getComponent(1), 3), myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight - 40);
		}
	}
```


![severalattimeswitched](https://user-images.githubusercontent.com/203877/44905036-231db980-ad11-11e8-83ee-8e22dfa195e0.PNG)

```

**Comment by carlesgutierrez** [comment]
I did this small fix to have them in order. 

```
		for (int i = 0; i < myAvgFlowRois.size(); i++) {
			
			averageFlow.setInput(opticalFlow.getVelocity());
			averageFlow.setRoi(myAvgFlowRois[i]);
		//second try required to draw and give results over actual averageFlow
			averageFlow.setInput(opticalFlow.getVelocity());
			averageFlow.setRoi(myAvgFlowRois[i]);

			averageFlow.update();
				
			averageFlow.drawInput(myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight, myAvgFlowRois[i].width*densityWidth, myAvgFlowRois[i].height*densityHeight);
			averageFlow.drawVisualizer(myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight, myAvgFlowRois[i].width*densityWidth, myAvgFlowRois[i].height*densityHeight);

			ofDrawBitmapStringHighlight("getStDevMagnitude -> " + ofToString(averageFlow.getStDevMagnitude(), 3), myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight - 20);
			ofDrawBitmapStringHighlight("getComponent 0 -> " + ofToString(averageFlow.getComponent(0), 3), myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight - 60);
			ofDrawBitmapStringHighlight("getComponent 1 -> " + ofToString(averageFlow.getComponent(1), 3), myAvgFlowRois[i].x*densityWidth, myAvgFlowRois[i].y*densityHeight - 40);
		}
```

But when I'm using more than 5 ROIs FPS is going down dramatically. 
There is a bottle neck here, aparently repeat N times -> averageFlow.update();

**Comment by moostrik** [comment]
Reading a texture from videoRAM to normalRAM is a very time consuming process. 
For your purpose it might be more sensible to first read the whole image to pixels and analyze the subsections second.

**Comment by carlesgutierrez** [comment]
That make sense! 

My first approach -> Use **ofxCv**FloatImage images to read inputFbo, then apply update (Average Calcs) for-each ROI and save average calcs of each ROI. Do you think is ok?
I've already tried, but I've got a weird error after update floatPixelData `convertGrayToFloat( IplImage* grayImg, IplImage* floatImg ) ` with my new Opencv Image. 

Do you thing there another easier way to do it? 
Probably not necessary to add opencvn addon, but It's a way to handle that image types and apply Rois easy.
