### ISSUE TITLE
Unable to complile example_core on Ubuntu 16.04LTS using make

### ISSUE THREAD

**Issue by suveergarg** [moostrik/ofxFlowTools#26]
![error1](https://user-images.githubusercontent.com/17459580/44999429-cc4b0500-afda-11e8-9c72-61914ca5410f.png)

The above contains the error screen.
"/home/suveer/Desktop/of_v0.10.0_linux64gcc5_release/addons/ofxFlowTools/src/core/ftUtil.cpp:239:2: error: control reaches end of non-void function [-Werror=return-type]
"

Any help will be much appreciated.

**Comment by moostrik** [comment]
seems like the return in the switch statement is fine for mac and win, but not for linux.
fixed in the latest build (in the Fluid-Rebuild branch)
