### ISSUE TITLE
OfxFlowTools compiling on Ubuntu 16.04 LTS, but particles not visible.

### ISSUE THREAD

**Issue by suveergarg** [moostrik/ofxFlowTools#27]
Hi, 
I am running example_core on Ubuntu 16.04 LTS, gcc5 and graphics card : Intel Corporation Haswell-ULT Integrated Graphics Controller.

The example compiled after I changed a few of the functions that were declared as non-void and were not returning any values. In any of the mode I just see the camera input. In mode two a flickering screen.
Any issues you know that might help overcome this ?
I faced a similar issue with ofxFluid, where it returned ofFbo: UNSUPPORTED BUFFER FRAME ERROR.

**Comment by moostrik** [comment]
Let me know if the latest update works for you.
It does work for me on ubuntu 18.10 with 2080Ti
