### ISSUE TITLE
ofxFlowTools compiling on windows 10 pro , OF version 9.8 , errors when the program runs.

### ISSUE THREAD

**Issue by Raspard** [moostrik/ofxFlowTools#28]
Hello @moostrik ,
The Program builds, but in console it throws this errors.

[notice ] ftDecayShader initialized:
[notice ] ftVelocityMaskShader initialized:
[notice ] ftEOGShader initialized:
[notice ] ftHSLShader initialized:
[notice ] ftContrastShader initialized:
[notice ] ftGaussianBlurShader initialized:
[notice ] ftLuminanceShader initialized:
[notice ] ftDisplayScalarShader initialized:
[ error ] ofShader: setupShaderFromSource(): GL_GEOMETRY_SHADER_EXT shader failed to compile
[ error ] ofShader: GL_GEOMETRY_SHADER_EXT shader reports:
ERROR: 0:4: 'texture2DRect' : undeclared identifier
ERROR: 0:4: 'texture2DRect' : no matching overloaded function found (using implicit conversion)
ERROR: 0:4: 'texture2DRect' : function is not known
ERROR: 0:4: 'xy' : field selection requires structure, vector, or matrix on left hand side
ERROR: 0:4: '=' :  cannot convert from 'uniform highp float' to '2-component vector of highp float'

[ error ] ofShader: GL_GEOMETRY_SHADER_EXT, offending line 4 :
            2    #extension GL_ARB_texture_rectangle : enable
            3    #extension GL_EXT_geometry_shader4: enable
            4   uniform sampler2DRect fieldTexture; uniform vec2 texResolution; uniform vec4 baseColor; uniform float vectorSize; uniform float maxArrowSize; void main(){ vec4 lineStart = gl_PositionIn[0]; vec2 uv = lineStart.xy * texResolution; vec2 line = texture2DRect(fieldTexture, uv).xy * vectorSize; if (length(line) > maxArrowSize) line = normalize(line) * maxArrowSize; vec4 lineEnd = lineStart + vec4(line, 0.0, 0.0); float alpha = 0.3 + 0.3 * (1.0 - length(line) / maxArrowSize); vec4 color = baseColor; color.w *= alpha; float arrowLength = 0.75 * length(line); vec2 nLine = normalize(line); float arrowAngleA = atan(nLine.y, nLine.x) + 0.1; float arrowAngleB = atan(nLine.y, nLine.x) - 0.1; vec4 arrowLineA = vec4(cos(arrowAngleA) ,sin(arrowAngleA), 0., 0.); vec4 arrowLineB = vec4(cos(arrowAngleB) ,sin(arrowAngleB), 0., 0.); arrowLineA = normalize(arrowLineA) * arrowLength; arrowLineB = normalize(arrowLineB) * arrowLength; vec4 arrowA = lineStart +arrowLineA; vec4 arrowB = lineStart +arrowLineB; gl_Position = gl_ModelViewProjectionMatrix * lineStart; gl_FrontColor = color; EmitVertex(); gl_Position = gl_ModelViewProjectionMatrix * lineEnd; gl_FrontColor = color; EmitVertex(); gl_Position = gl_ModelViewProjectionMatrix * arrowA; gl_FrontColor = color; EmitVertex(); gl_Position = gl_ModelViewProjectionMatrix * lineEnd; gl_FrontColor = color; EmitVertex(); gl_Position = gl_ModelViewProjectionMatrix * arrowB; gl_FrontColor = color; EmitVertex(); EndPrimitive(); }
            5

[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
Attached geometry shader is not compiled.

[warning] ftVelocityFieldShader failed to initialize:
[notice ] ftDiffuseShader initialized:
[notice ] ftAdvectShader initialized:
[notice ] ftDivergenceShader initialized:
[notice ] ftJacobiShader initialized:
[notice ] ftSubstractGradient initialized:
[notice ] ftSmokeBuoyancyShader initialized:
[notice ] ftVorticityFirstPassShader initialized:
[notice ] ftVorticitySecondPassShader initialized:
[notice ] ftAddForceShader initialized:
[notice ] ftClampLengthShader initialized:
[notice ] ftInitPositionShader initialized:
[notice ] ftDrawParticleShader initialized:
[notice ] ftMoveParticleShader initialized:
[notice ] ftAgeLifespanMassSizeParticleShader initialized:
[notice ] ftAddForceShader initialized:
[notice ] ftDisplayScalarShader initialized:
[notice ] ftDisplayScalarShader initialized:
[ error ] ofShader: setupShaderFromSource(): GL_GEOMETRY_SHADER_EXT shader failed to compile
[ error ] ofShader: GL_GEOMETRY_SHADER_EXT shader reports:
ERROR: 0:4: 'texture2DRect' : undeclared identifier
ERROR: 0:4: 'texture2DRect' : no matching overloaded function found (using implicit conversion)
ERROR: 0:4: 'texture2DRect' : function is not known
ERROR: 0:4: 'xy' : field selection requires structure, vector, or matrix on left hand side
ERROR: 0:4: '=' :  cannot convert from 'uniform highp float' to '2-component vector of highp float'

[ error ] ofShader: GL_GEOMETRY_SHADER_EXT, offending line 4 :
            2    #extension GL_ARB_texture_rectangle : enable
            3    #extension GL_EXT_geometry_shader4: enable
            4   uniform sampler2DRect fieldTexture; uniform vec2 texResolution; uniform vec4 baseColor; uniform float vectorSize; uniform float maxArrowSize; void main(){ vec4 lineStart = gl_PositionIn[0]; vec2 uv = lineStart.xy * texResolution; vec2 line = texture2DRect(fieldTexture, uv).xy * vectorSize; if (length(line) > maxArrowSize) line = normalize(line) * maxArrowSize; vec4 lineEnd = lineStart + vec4(line, 0.0, 0.0); float alpha = 0.3 + 0.3 * (1.0 - length(line) / maxArrowSize); vec4 color = baseColor; color.w *= alpha; float arrowLength = 0.75 * length(line); vec2 nLine = normalize(line); float arrowAngleA = atan(nLine.y, nLine.x) + 0.1; float arrowAngleB = atan(nLine.y, nLine.x) - 0.1; vec4 arrowLineA = vec4(cos(arrowAngleA) ,sin(arrowAngleA), 0., 0.); vec4 arrowLineB = vec4(cos(arrowAngleB) ,sin(arrowAngleB), 0., 0.); arrowLineA = normalize(arrowLineA) * arrowLength; arrowLineB = normalize(arrowLineB) * arrowLength; vec4 arrowA = lineStart +arrowLineA; vec4 arrowB = lineStart +arrowLineB; gl_Position = gl_ModelViewProjectionMatrix * lineStart; gl_FrontColor = color; EmitVertex(); gl_Position = gl_ModelViewProjectionMatrix * lineEnd; gl_FrontColor = color; EmitVertex(); gl_Position = gl_ModelViewProjectionMatrix * arrowA; gl_FrontColor = color; EmitVertex(); gl_Position = gl_ModelViewProjectionMatrix * lineEnd; gl_FrontColor = color; EmitVertex(); gl_Position = gl_ModelViewProjectionMatrix * arrowB; gl_FrontColor = color; EmitVertex(); EndPrimitive(); }
            5

[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
Attached geometry shader is not compiled.

[warning] ftVelocityFieldShader failed to initialize:

**Comment by moostrik** [comment]
If you want to use flowtools with of 0.9.8 check the 0.9.8 branch of flowtools
