### ISSUE TITLE
Examples not working on 2018 Retina MBP

### ISSUE THREAD

**Issue by tyhenry** [moostrik/ofxFlowTools#29]
This only occurs using programmable renderer - everything works fine when switching to fixed pipeline.

Specifically, it seems like there's an issue with the inputFbo / ping pong processing for optical flow - when I try to visualize the optical flow input ("input for velocity") in the examples, the image flickers to black every other frame - here's a screen capture:
https://imgur.com/ZST5hUT

This occurs on master branch and Fluid-Rebuild.

GPU is Radeon Pro 560X 4096 MB.  

Examples are working normally using programmable renderer on a 2013 MBP with Nvidia GeForce GT 750M, so maybe an AMD / NVidia driver or implementation issue?

**Comment by moostrik** [comment]
Yes, There seems to be a problem with the pingpongFbo on Radeon and possible other non Nvidia graphics cards. Unfortunately I did not have the time to look deeper into the issue. I hope I will find some time (and a radeon machine) in the next month or so...

**Comment by tyhenry** [comment]
I may have some time to debug for AMD.  Any thoughts about what the issue might be?
I'm actually working on a [new branch](https://github.com/tyhenry/ofxFlowTools/tree/pingpong) already to test dual fbo instead of multiple color attachments (based on [this reddit thread](https://www.reddit.com/r/opengl/comments/1rsnhy/most_efficient_fbo_usage_in_multipass_pipeline/) and [p.65 of this presentation from nVidia / Valve](https://developer.nvidia.com/sites/default/files/akamai/gamedev/docs/Porting%20Source%20to%20Linux.pdf)).

**Comment by moostrik** [comment]
Looks good!
Thanks
I looked into the possibility to keep my new pingpongfbo, but it leads to a lot of weird behaviour.

**Comment by Aurelian24** [comment]
Im having the same Issue. 


Versión for 0.9.8 works fine. 

but versión in 0.10.1 doesn´t work. It compiles and everything but I can´t see neither the fluid or particles or whatever. Its weird. 

I´ve tryed @tyhenry branch, but is now working. 
 

Im using windows. 

This are my specs :  
AMD Ryzen 5 1600 Six-Core processor
16GBS RAM 
NVIDIA GeForce GTX 1060 6GBS

**Comment by ICapalija** [comment]
I got a similar problem on MacBookPro 2018,
the GUI and camera input are visible, but there are no particles.
You mentioned that:
> A discrete graphics card is highly recommended.

Does that mean that it will work without GPU?

Thank you for the great addon!

**Comment by moostrik** [comment]
try the latest update to the master branch, it should fix a lot of issues.
It should work on integrated intel gpu's, although my recommendation still stands
