### ISSUE TITLE
[warning] ofGraphics: ofPushStyle():

### ISSUE THREAD

**Issue by TheHmmka** [moostrik/ofxFlowTools#4]
Always get this:
[warning] ofGraphics: ofPushStyle(): maximum number of style pushes << 32 reached, did you forget to pop somewhere?
And no particles :-(
Mac Os 10.10
Any suggestions?

**Comment by moostrik** [comment]
pop fixed

what kind of computer / videocard are you using?

**Comment by TheHmmka** [comment]
MacBookPro10,2
Intel Core i5
Intel HD Graphics 4000
32-Bit Color (ARGB8888) Retina

**Comment by TheHmmka** [comment]
And with init I got:

[warning] Framebuffer with id: cannot be bound onto itself. 
Most probably you forgot to end() the current framebuffer before calling begin() again.
[ error ] unbalanced fbo bind/unbind binding default framebuffer

May be this is a reason. I am also switch of USE_PROGRAMMABLE_GL.

**Comment by moostrik** [comment]
The addon is made for discrete videocards from nvidia or ati.
I'm surprised it works on the hd4000 at all.

My macbook also has the hd4000, but i could not reproduce the error.
The particles work

**Comment by moostrik** [comment]
If you can find more about this bug let me know

**Comment by TheHmmka** [comment]
Thanks, will try to figure out.
