### ISSUE TITLE
issue with timeBlurShader inside ftOpticalFlow on windows.

### ISSUE THREAD

**Issue by julapy** [moostrik/ofxFlowTools#8]
hey, im seeing an issue with timeBlurShader inside ftOpticalFlow on Windows using latest OF 0.9.0 (but i also think this is happening in master too). 
works fine on OSX with latest OF 0.9.0,
but on windows the timeBlurShader doesn't work.

looking into it now... but thought id post here just in case you might have some ideas on this.

cheers.

**Comment by moostrik** [comment]
Yes this is a long standing bug, unfortunately i have no windows system to test it on for the moment.

**Comment by tdubnov** [comment]
Did you find a solution to this by chance?
