### ISSUE TITLE
Issue on windows / linux and oF 0.9.0

### ISSUE THREAD

**Issue by charlesveasey** [moostrik/ofxFlowTools#9]
Camera has no effect in the example on windows / linux and oF 0.9.0.

Everything seems to work properly when the camera is unplugged and modifications are made with the mouse.

**Comment by Wenzy--** [comment]
the same on Mac.

[ error ] ofGLUtils: ofGetGLFormatFromInternal(): unknown internal format 6403, returning GL_RGBA
[ error ] ofGLUtils: ofGetGlTypeFromInternal(): unknown internal format 6403, returning GL_UNSIGNED_BYTE
[ error ] ofGLUtils: ofGetGLFormatFromInternal(): unknown internal format 6403, returning GL_RGBA
[ error ] ofGLUtils: ofGetGlTypeFromInternal(): unknown internal format 6403, returning GL_UNSIGNED_BYTE
[ error ] ofGLUtils: ofGetGLFormatFromInternal(): unknown internal format 6403, returning GL_RGBA
[ error ] ofGLUtils: ofGetGlTypeFromInternal(): unknown internal format 6403, returning GL_UNSIGNED_BYTE

**Comment by moostrik** [comment]
Unfortunately i cannot reproduce the error (on mac)
